import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const collections = [
  { handle: "grinding", title: "Concrete Grinding & Polishing", bay: "01", description: "Walk-behind planetary grinders for commercial slabs." },
  { handle: "injection", title: "Concrete Crack Injection", bay: "02", description: "Epoxy and polyurethane pumps for structural and leaking cracks." },
  { handle: "crack-sealing", title: "Asphalt Crack Sealing", bay: "03", description: "Hot-melt kettles for parking lots and commercial asphalt." },
  { handle: "soda", title: "Soda & Sand Blasting", bay: "04", description: "Portable blast pots and recovery units for paint and coating removal." },
  { handle: "laser", title: "Laser Cleaning", bay: "05", description: "Handheld fiber laser carts that strip rust and paint without media." },
  { handle: "pressure-wash", title: "Commercial Pressure Washing", bay: "06", description: "Gas-powered cart washers for lots, docks, and building exteriors." },
  { handle: "lot-painting", title: "Parking Lot Painting", bay: "07", description: "Walk-behind cold-paint stripers for stalls, arrows, and hash." },
  { handle: "caulking", title: "Commercial Caulking", bay: "08", description: "Dual-cartridge epoxy and caulk guns for joints and structural adhesives." },
];

const faqs = (topic) => [
  { q: "Is this commercial-duty?", a: `Yes. Pavora ${topic} equipment is specified for contractor crews.` },
  { q: "Do you train the crew?", a: "Remote start-up is included. On-site days are quoted separately." },
  { q: "What about freight?", a: "Commercial freight in the contiguous U.S. Liftgate on request." },
];

let n = 1;
const products = [];

function add(p) {
  const id = `pv-${String(n).padStart(3, "0")}`;
  const sku = `PV-${String(n).padStart(4, "0")}`;
  n += 1;
  const quoteOnly = p.price >= 15000;
  products.push({
    id,
    handle: p.handle,
    title: p.title,
    description: p.description,
    collection: p.collection,
    price: p.price,
    compareAtPrice: p.compareAtPrice ?? null,
    currency: "USD",
    sku,
    brand: "Pavora",
    equipmentType: p.equipmentType,
    tradeTypes: p.tradeTypes,
    contractorTypes: p.contractorTypes,
    useCase: p.useCase ?? "commercial",
    warrantyYears: p.warrantyYears ?? 2,
    financing: p.price >= 800,
    quoteOnly,
    inStock: p.inStock ?? true,
    highlight: p.highlight,
    leadTime: quoteOnly ? "Quoted lead time, typically 2–5 weeks" : "Ships in 5–12 business days",
    power: p.power,
    dimensions: p.dimensions,
    weightLbs: p.weightLbs,
    applications: p.applications,
    intendedUsers: p.intendedUsers,
    benefits: p.benefits,
    included: p.included,
    installation: p.installation ?? "Yard delivery. Commissioning video included.",
    training: p.training ?? "Remote crew walkthrough included.",
    shipping: "Commercial freight, contiguous U.S. Liftgate on request.",
    replacementParts: "Wear parts stocked for 7 years from purchase date.",
    faqs: faqs(p.equipmentType.toLowerCase()),
    featured: Boolean(p.featured),
    tags: p.tags,
    image: p.image,
    monthly: Math.max(1, Math.round(p.price / 36)),
  });
}

const concrete = ["Concrete contractors", "Flooring crews", "Parking garage restorers"];
const pave = ["Paving contractors", "Property managers", "Municipal crews"];
const stripe = ["Striping contractors", "Parking lot painters"];
const blast = ["Blasting contractors", "Industrial cleaners", "Restoration crews"];
const envelope = ["Restoration contractors", "Glazing crews", "General contractors"];

const rows = [
  {
    handle: "pavora-mill-27-planetary-grinder",
    title: "Pavora Mill-27 Planetary Grinder",
    collection: "grinding",
    equipmentType: "Planetary floor grinder",
    price: 12800,
    featured: true,
    highlight: "Four-head planetary for grind, hone, and polish on warehouse slabs",
    power: "230V 1Ø / 480V 3Ø",
    dimensions: '27" working width',
    weightLbs: 486,
    tradeTypes: ["grinding", "polishing"],
    contractorTypes: ["concrete contractor", "restoration contractor"],
    tags: ["grinder", "planetary", "concrete"],
    applications: ["Remove coatings", "Hone and polish", "Expose aggregate", "Prep for overlay"],
    intendedUsers: concrete,
    benefits: ["Even scratch pattern", "Dust skirt", "Tool-free head change"],
    included: ["Planetary chassis", "Starter diamond set", "Dust skirt"],
    image: "/media/catalog/grinder.webp",
    description: "A walk-behind planetary floor grinder for commercial slabs. This is the machine in the photo: yellow chassis, four-head deck, operator handles.",
  },
  {
    handle: "pavora-injecta-ep-pump",
    title: "Pavora Injecta-EP Epoxy Pump",
    collection: "injection",
    equipmentType: "Epoxy injection pump",
    price: 5600,
    featured: true,
    highlight: "High-pressure grouting pump for structural cracks in slabs, walls, and decks",
    power: "120V drill drive",
    dimensions: "18 × 14 × 28 in",
    weightLbs: 64,
    tradeTypes: ["crack injection", "structural repair"],
    contractorTypes: ["concrete contractor", "restoration contractor"],
    tags: ["epoxy", "injection", "pump"],
    applications: ["Structural cracks", "Deck soffits", "Walls and columns"],
    intendedUsers: concrete,
    benefits: ["Pressure gauge", "Portable stand", "Flush kit included"],
    included: ["Pump", "Hopper", "Hoses", "Packers starter"],
    image: "/media/catalog/pump.webp",
    description: "A high-pressure injection grouting pump with hopper, gauge, and stand. Used to push epoxy into structural cracks — not a caulk gun.",
  },
  {
    handle: "pavora-injecta-pu-pump",
    title: "Pavora Injecta-PU Poly Pump",
    collection: "injection",
    equipmentType: "Polyurethane injection pump",
    price: 4800,
    highlight: "Water-stop polyurethane kit with hose, wand, and hard case",
    power: "120V drill drive",
    dimensions: "Kit case 22 in",
    weightLbs: 48,
    tradeTypes: ["crack injection", "waterproofing"],
    contractorTypes: ["concrete contractor", "restoration contractor"],
    tags: ["polyurethane", "injection", "leak"],
    applications: ["Leaking cracks", "Cold joints", "Below-grade walls"],
    intendedUsers: concrete,
    benefits: ["Full kit in case", "Pressure gauge", "Injection wand"],
    included: ["Pump", "Hopper", "Hose", "Wand", "Hard case"],
    image: "/media/catalog/pump2.webp",
    description: "Polyurethane injection pump kit: pump body, hopper, hose, wand, and case. Stops water in parking decks and foundation walls.",
  },
  {
    handle: "pavora-melt-120-melter",
    title: "Pavora Melt-120 Crack Melter",
    collection: "crack-sealing",
    equipmentType: "Asphalt crack sealer",
    price: 9800,
    featured: true,
    highlight: "Walk-behind hot-melt kettle for parking-lot crack programs",
    power: "Gasoline engine + burner",
    dimensions: "Walk-behind 48 in",
    weightLbs: 420,
    tradeTypes: ["crack sealing", "asphalt"],
    contractorTypes: ["paving contractor", "property management"],
    tags: ["melter", "kettle", "asphalt"],
    applications: ["Parking lots", "Drives", "Commercial asphalt"],
    intendedUsers: pave,
    benefits: ["Heated hose", "Agitated kettle", "Walk-behind"],
    included: ["Kettle", "Insulated hose", "Wand"],
    image: "/media/catalog/kettle.webp",
    description: "A walk-behind asphalt crack sealer: heated kettle, insulated hose, and applicator wand. The machine in the photo is the listing.",
  },
  {
    handle: "pavora-soda-pro-250",
    title: "Pavora Soda-Pro 250",
    collection: "soda",
    equipmentType: "Portable blast pot",
    price: 6400,
    featured: true,
    highlight: "Wheeled pressure pot for soda or sand blasting",
    power: "Requires 185 cfm air",
    dimensions: "Pot 36 in",
    weightLbs: 210,
    tradeTypes: ["soda blasting", "sand blasting"],
    contractorTypes: ["blasting contractor", "restoration contractor"],
    tags: ["blast", "soda", "pot"],
    applications: ["Buildings", "Machinery", "Vehicles", "Paint removal"],
    intendedUsers: blast,
    benefits: ["Wheeled pot", "Metering valve", "Deadman hose"],
    included: ["Pot", "Hose", "Nozzle", "Helmet"],
    image: "/media/catalog/blast.webp",
    description: "A portable pressure blast pot on a wheeled frame with hose and nozzle. Use soda or sand — this is the pot, not a grinder.",
  },
  {
    handle: "pavora-media-vac-recovery",
    title: "Pavora Media-Vac Recovery",
    collection: "soda",
    equipmentType: "Recovery blast pot",
    price: 4800,
    highlight: "Blast pot with built-in vacuum recovery and dust filter",
    power: "230V + air",
    dimensions: "Vac 28 × 22 × 40 in",
    weightLbs: 142,
    tradeTypes: ["soda blasting", "cleanup"],
    contractorTypes: ["blasting contractor"],
    tags: ["vac", "recovery", "blast"],
    applications: ["Interior blast", "Shops", "Occupied sites"],
    intendedUsers: blast,
    benefits: ["Onboard filter", "Caster base", "Recovery hoses"],
    included: ["Recovery pot", "Filter", "Hoses"],
    image: "/media/catalog/blast2.webp",
    description: "A red recovery blast pot with filter cartridge and caster base. Recovers media instead of leaving it on the floor.",
  },
  {
    handle: "pavora-lase-200-fiber",
    title: "Pavora Lase-200 Fiber Cleaner",
    collection: "laser",
    equipmentType: "Handheld fiber laser cleaner",
    price: 28500,
    featured: true,
    highlight: "Cart-mounted fiber laser with handheld gun — strip rust and paint without grit",
    power: "240V 1Ø",
    dimensions: "Cart 32 × 22 × 44 in",
    weightLbs: 186,
    tradeTypes: ["laser cleaning", "surface prep"],
    contractorTypes: ["blasting contractor", "restoration contractor"],
    tags: ["laser", "rust", "cleaning"],
    applications: ["Rust", "Paint", "Molds", "Welds"],
    intendedUsers: blast,
    benefits: ["No media waste", "Handheld gun", "Wheeled cart"],
    included: ["Laser cart", "Handheld gun", "Umbilical", "Goggles"],
    image: "/media/catalog/laser.webp",
    description: "A wheeled fiber laser cleaning cart with the handheld gun coiled on top. This is the machine you see on DHgate when you search laser cleaner.",
  },
  {
    handle: "pavora-wash-cart-2700",
    title: "Pavora Wash-Cart 2700",
    collection: "pressure-wash",
    equipmentType: "Gas pressure washer",
    price: 3200,
    featured: true,
    highlight: "2700 PSI gas cart washer for lots, docks, and exteriors",
    power: "Gasoline engine",
    dimensions: "Cart 28 in",
    weightLbs: 72,
    tradeTypes: ["pressure washing"],
    contractorTypes: ["restoration contractor", "property management"],
    tags: ["pressure wash", "gas", "cart"],
    applications: ["Lots", "Docks", "Building exteriors", "Sidewalks"],
    intendedUsers: ["Pressure-wash contractors", "Property managers"],
    benefits: ["2700 PSI", "Quick-connect tips", "Soap tank"],
    included: ["Washer", "Wand", "Hose", "Tip set"],
    image: "/media/catalog/washer-cart.webp",
    description: "A gas-powered pressure washer on a wheeled cart: engine, wand, hose, and soap tank. The listing photo is this machine.",
  },
  {
    handle: "pavora-lotline-walk",
    title: "Pavora Lotline Walk",
    collection: "lot-painting",
    equipmentType: "Walk-behind line striper",
    price: 5400,
    featured: true,
    highlight: "Cold-paint walk-behind for stalls, arrows, and hash marks",
    power: "Gasoline engine",
    dimensions: "Walk-behind 40 in",
    weightLbs: 148,
    tradeTypes: ["parking lot painting", "striping"],
    contractorTypes: ["striping contractor", "paving contractor"],
    tags: ["striper", "parking lot", "paint"],
    applications: ["Stalls", "Arrows", "Hash", "Fire lanes"],
    intendedUsers: stripe,
    benefits: ["Adjustable line width", "Bead spreader", "Walk-behind"],
    included: ["Striper", "Gun", "Bead hopper"],
    image: "/media/catalog/striper.webp",
    description: "A walk-behind cold-paint road marking machine. This is a line striper — not a pressure washer and not a grinder.",
  },
  {
    handle: "pavora-seal-gun-dual",
    title: "Pavora Seal-Gun Dual",
    collection: "caulking",
    equipmentType: "Dual-cartridge epoxy gun",
    price: 890,
    featured: true,
    highlight: "Manual 1:1 dual-cartridge gun for epoxy and structural adhesives",
    power: "None",
    dimensions: "Gun 24 in",
    weightLbs: 6,
    tradeTypes: ["caulking", "epoxy"],
    contractorTypes: ["restoration contractor", "glazing contractor"],
    tags: ["caulk", "epoxy", "dual gun"],
    applications: ["Joints", "Anchors", "Crack face seal", "Facades"],
    intendedUsers: envelope,
    benefits: ["1:1 dual plunger", "Manual trigger", "Cartridge cradle"],
    included: ["Dual gun", "Nozzle set"],
    image: "/media/catalog/caulk.webp",
    description: "A red dual-cartridge epoxy applicator gun. Two plungers, one trigger. This is a glue gun for two-part adhesive — not a drill.",
  },
];

for (const row of rows) add(row);

const catalog = {
  brand: "Pavora",
  generatedAt: new Date().toISOString(),
  collections,
  products,
};

writeFileSync(join(root, "data", "catalog.json"), JSON.stringify(catalog, null, 2));
console.log(`Wrote ${products.length} products across ${collections.length} collections`);
