import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const collections = [
  { handle: "grinding", title: "Concrete Grinding & Polishing", bay: "01", description: "Grind old slabs, polish, expose aggregate, and finish commercial floors." },
  { handle: "injection", title: "Concrete Crack Injection", bay: "02", description: "Epoxy and polyurethane pumps for structural and non-structural crack repair." },
  { handle: "leveling", title: "Polyurethane Concrete Leveling", bay: "03", description: "Foam injection rigs that raise sunken slabs through small drilled ports." },
  { handle: "crack-sealing", title: "Asphalt Crack Sealing", bay: "04", description: "Melters, wands, and kettles for parking lots, drives, and commercial asphalt." },
  { handle: "sealcoating", title: "Asphalt Sealcoating", bay: "05", description: "Spray and squeegee systems that coat aging asphalt before striping." },
  { handle: "thermoplastic", title: "Thermoplastic Road Marking", bay: "06", description: "Durable markings for roads, crosswalks, bike lanes, and parking areas." },
  { handle: "marking-removal", title: "Pavement Marking Removal", bay: "07", description: "Grind, water-blast, or shot-erase old lines, arrows, and legends." },
  { handle: "dry-ice", title: "Dry-Ice Blasting", bay: "08", description: "Non-abrasive CO₂ cleaning for machinery, electrics, molds, and restoration." },
  { handle: "soda", title: "Soda Blasting", bay: "09", description: "Remove paint, grime, and coatings from buildings, machinery, and vehicles." },
  { handle: "laser", title: "Laser Cleaning", bay: "10", description: "Fiber laser systems that strip rust, paint, and residue without media waste." },
  { handle: "pressure-wash", title: "Commercial Pressure Washing", bay: "11", description: "Hot and cold washers for warehouses, garages, docks, and building exteriors." },
  { handle: "lot-painting", title: "Parking Lot Painting", bay: "12", description: "Walk-behind and ride-on stripers, stencils, and airless lot painters." },
  { handle: "drone", title: "Drone Roof Inspections", bay: "13", description: "RTK drones and reporting stations for commercial roof photography." },
  { handle: "thermal", title: "Thermal Roof Leak Detection", bay: "14", description: "Infrared arrays that find moisture without tearing the roof apart." },
  { handle: "expansion-joints", title: "Expansion-Joint Replacement", bay: "15", description: "Saws, fill pumps, and kits for garage and structural joint work." },
  { handle: "caulking", title: "Commercial Caulking & Joint Sealing", bay: "16", description: "Bulk guns and facade pumps for windows, joints, and penetrations." },
  { handle: "garage", title: "Parking Garage Restoration", bay: "17", description: "Combined concrete repair, injection, waterproofing, striping, and coatings." },
  { handle: "parts", title: "Consumables & Wear Parts", bay: "18", description: "Cups, media, beads, foam, paint, tips, and filters stocked for the yard." },
  { handle: "packages", title: "Crew Packages", bay: "19", description: "Turnkey invoices for a first crew or a second truck." },
];

const media = {
  grinding: ["/media/gear/polisher.jpg", "/media/gear/px-grinder.jpg", "/media/gear/px-sparks.jpg"],
  injection: ["/media/gear/us-tools.jpg", "/media/gear/px-plant.jpg", "/media/gear/px-cnc.jpg"],
  leveling: ["/media/gear/us-tools.jpg", "/media/gear/px-plant.jpg", "/media/gear/px-tools2.jpg"],
  "crack-sealing": ["/media/gear/px-spray.jpg", "/media/gear/px-plant.jpg", "/media/gear/px-spray2.jpg"],
  sealcoating: ["/media/gear/px-spray.jpg", "/media/gear/px-spray2.jpg", "/media/gear/px-wash.jpg"],
  thermoplastic: ["/media/gear/px-spray.jpg", "/media/gear/px-wash2.jpg", "/media/gear/px-spray2.jpg"],
  "marking-removal": ["/media/gear/px-sparks.jpg", "/media/gear/px-grinder.jpg", "/media/gear/polisher.jpg"],
  "dry-ice": ["/media/gear/blaster.jpg", "/media/gear/px-sparks.jpg", "/media/gear/px-cnc.jpg"],
  soda: ["/media/gear/blaster.jpg", "/media/gear/px-grinder.jpg", "/media/gear/px-sparks.jpg"],
  laser: ["/media/gear/us-cnc.jpg", "/media/gear/px-cnc.jpg", "/media/gear/px-sparks.jpg", "/media/gear/us-elec.jpg"],
  "pressure-wash": ["/media/gear/px-wash.jpg", "/media/gear/px-wash2.jpg", "/media/gear/px-spray2.jpg"],
  "lot-painting": ["/media/gear/px-spray.jpg", "/media/gear/px-spray2.jpg", "/media/gear/px-wash.jpg"],
  drone: ["/media/gear/px-drone2.jpg", "/media/gear/px-drone.jpg", "/media/gear/us-drone.jpg"],
  thermal: ["/media/gear/us-cnc.jpg", "/media/gear/us-elec.jpg", "/media/gear/px-indust.jpg"],
  "expansion-joints": ["/media/gear/px-sparks.jpg", "/media/gear/polisher.jpg", "/media/gear/px-grinder.jpg"],
  caulking: ["/media/gear/px-spray.jpg", "/media/gear/us-tools.jpg", "/media/gear/px-tools2.jpg"],
  garage: ["/media/gear/polisher.jpg", "/media/gear/blaster.jpg", "/media/gear/px-spray.jpg", "/media/gear/px-weld.jpg"],
  parts: ["/media/gear/px-grinder.jpg", "/media/gear/us-tools.jpg", "/media/gear/px-tools2.jpg", "/media/gear/px-indust.jpg"],
  packages: ["/media/gear/polisher.jpg", "/media/gear/blaster.jpg", "/media/gear/px-spray.jpg", "/media/gear/px-crane.jpg"],
};

const mediaIndex = {};
function nextImage(collection) {
  const list = media[collection] || ["/media/gear/polisher.jpg"];
  const i = mediaIndex[collection] || 0;
  mediaIndex[collection] = i + 1;
  return list[i % list.length];
}

const faqs = (topic) => [
  { q: "Is this commercial-duty?", a: `Yes. Pavora ${topic} equipment is specified for contractor crews, not weekend rental-counter toys.` },
  { q: "Do you train the crew?", a: "Remote start-up is included. On-site days are quoted for packages and quote-only rigs." },
  { q: "What about freight?", a: "Commercial freight in the contiguous U.S. Liftgate on request. Trailers and ride-ons ship crated." },
];

let n = 1;
const products = [];

function add(p) {
  const id = `pv-${String(n).padStart(3, "0")}`;
  const sku = `PV-${String(n).padStart(4, "0")}`;
  n += 1;
  const quoteOnly = p.price >= 15000;
  const monthly = Math.max(1, Math.round(p.price / 36));
  products.push({
    id,
    handle: p.handle,
    title: p.title,
    description: p.description,
    collection: p.collection,
    price: p.price,
    compareAtPrice: p.compareAtPrice ?? null,
    currency: "USD",
    sku,
    brand: "Pavora",
    equipmentType: p.equipmentType,
    tradeTypes: p.tradeTypes,
    contractorTypes: p.contractorTypes,
    useCase: p.useCase ?? "commercial",
    warrantyYears: p.warrantyYears ?? (p.collection === "parts" ? 0 : 2),
    financing: p.price >= 800,
    quoteOnly,
    inStock: p.inStock ?? true,
    highlight: p.highlight,
    leadTime: quoteOnly ? "Quoted lead time, typically 2–5 weeks" : "Ships in 5–12 business days",
    power: p.power,
    dimensions: p.dimensions,
    weightLbs: p.weightLbs,
    applications: p.applications,
    intendedUsers: p.intendedUsers,
    benefits: p.benefits,
    included: p.included,
    installation: p.installation ?? "Yard delivery. Commissioning video included. On-site start-up quoted for trailers and ride-ons.",
    training: p.training ?? "Remote crew walkthrough included. OSHA-aware jobsite briefing available on packages.",
    shipping: "Commercial freight, contiguous U.S. Liftgate on request. Alaska/Hawaii quoted.",
    replacementParts: "Wear parts stocked for 7 years from purchase date.",
    faqs: faqs(p.equipmentType.toLowerCase()),
    featured: Boolean(p.featured),
    tags: p.tags,
    image: p.image || nextImage(p.collection),
    monthly,
  });
}

const concreteUsers = ["Concrete contractors", "Flooring crews", "Parking garage restorers"];
const paveUsers = ["Paving contractors", "Property managers", "Municipal crews"];
const stripeUsers = ["Striping contractors", "Parking lot painters", "DOT subcontractors"];
const blastUsers = ["Blasting contractors", "Industrial cleaners", "Restoration crews"];
const roofUsers = ["Roofing contractors", "Building inspectors", "Property managers"];
const envelopeUsers = ["Restoration contractors", "Glazing crews", "General contractors"];

const rows = [
  { handle: "pavora-mill-27-planetary-grinder", title: "Pavora Mill-27 Planetary Grinder", collection: "grinding", equipmentType: "Planetary floor grinder", price: 12800, featured: true, highlight: "Three-head planetary for grind, hone, and polish on warehouse slabs", power: "230V 1Ø / 480V 3Ø", dimensions: '27" working width', weightLbs: 486, tradeTypes: ["grinding", "polishing", "expose aggregate"], contractorTypes: ["concrete contractor", "restoration contractor", "parking garage"], tags: ["grinder", "polish", "concrete", "dust"], applications: ["Remove coatings", "Hone and polish", "Expose aggregate", "Prep for overlay"], intendedUsers: concreteUsers, benefits: ["Even scratch pattern", "HEPA vac ports", "Tool-free head change"], included: ["Planetary chassis", "Starter diamond set", "Dust skirt", "Transport cart"], description: "A 27-inch planetary grinder for commercial floors that have to look finished, not just flat. Built for grind-and-seal, polish, and aggregate exposure." },
  { handle: "pavora-dens-7-edge-grinder", title: "Pavora Dens-7 Edge Grinder", collection: "grinding", equipmentType: "Edge grinder", price: 4200, highlight: "Gets the last 7 inches the planetary cannot reach", power: "120V 15A", dimensions: '7" cup, 18" chassis', weightLbs: 92, tradeTypes: ["grinding", "edge work"], contractorTypes: ["concrete contractor"], tags: ["edge", "grinder", "concrete"], applications: ["Wall lines", "Columns", "Stair landings"], intendedUsers: concreteUsers, benefits: ["Low profile", "Vac port", "Variable speed"], included: ["Edge grinder", "Two cups", "Vac hose adapter"], description: "Compact edge grinder for columns, walls, and landings so the floor does not show a 7-inch unground halo." },
  { handle: "pavora-polish-pro-burnisher", title: "Pavora Polish-Pro Burnisher", collection: "grinding", equipmentType: "High-speed burnisher", price: 8900, featured: true, highlight: "High-speed polish after densifier for retail and lobby floors", power: "230V", dimensions: '27" pad', weightLbs: 210, tradeTypes: ["polishing"], contractorTypes: ["concrete contractor", "flooring contractor"], tags: ["polish", "burnish", "concrete"], applications: ["Final polish", "Maintenance shine", "Retail floors"], intendedUsers: concreteUsers, benefits: ["Pad pressure control", "Dust containment", "Quiet enough for occupied buildings"], included: ["Burnisher", "Starter pads", "Dust skirt"], description: "Commercial burnisher for the last passes after densifier. Built for occupied retail, not a buffer from the janitorial closet." },
  { handle: "pavora-hepa-vac-prop", title: "Pavora HEPA-Vac Prop", collection: "grinding", equipmentType: "HEPA dust extractor", price: 3400, highlight: "Pairs with grinders so silica stays in the bag", power: "120V 20A", dimensions: "24 × 24 × 48 in", weightLbs: 118, tradeTypes: ["dust control", "grinding"], contractorTypes: ["concrete contractor"], tags: ["hepa", "silica", "vac"], applications: ["Grinder extraction", "Saw cutting", "Joint work"], intendedUsers: concreteUsers, benefits: ["HEPA filtration", "Auto-clean pulse", "Long hose"], included: ["Extractor", "Hose", "Wand", "Filter set"], description: "HEPA extractor sized for planetary and edge grinders. Silica compliance is not optional on commercial floors." },
  { handle: "pavora-injecta-ep-pump", title: "Pavora Injecta-EP Epoxy Pump", collection: "injection", equipmentType: "Epoxy injection pump", price: 5600, featured: true, highlight: "Metered epoxy for structural cracks in slabs, walls, and decks", power: "120V", dimensions: "18 × 14 × 28 in", weightLbs: 64, tradeTypes: ["crack injection", "structural repair"], contractorTypes: ["concrete contractor", "restoration contractor", "parking garage"], tags: ["epoxy", "injection", "crack"], applications: ["Structural cracks", "Deck soffits", "Walls and columns"], intendedUsers: concreteUsers, benefits: ["Ratio control", "Low-pressure start", "Flush kit included"], included: ["Pump", "Hoses", "Packers starter", "Flush kit"], description: "Two-component epoxy injection pump for structural crack repair. Metered so the resin actually fills the crack instead of decorating the face." },
  { handle: "pavora-injecta-pu-pump", title: "Pavora Injecta-PU Poly Pump", collection: "injection", equipmentType: "Polyurethane injection pump", price: 4800, highlight: "Water-stop polyurethane for leaking cracks and joints", power: "120V", dimensions: "16 × 12 × 24 in", weightLbs: 48, tradeTypes: ["crack injection", "waterproofing"], contractorTypes: ["concrete contractor", "restoration contractor", "parking garage"], tags: ["polyurethane", "leak", "injection"], applications: ["Leaking cracks", "Cold joints", "Below-grade walls"], intendedUsers: concreteUsers, benefits: ["Moisture-tolerant resins", "Portable", "Easy flush"], included: ["Pump", "Wand", "Packers", "Resin starter"], description: "Polyurethane injection pump for non-structural leaks. Stops water in parking decks and foundation walls without tearing the slab open." },
  { handle: "pavora-port-pack-crack-kit", title: "Pavora Port-Pack Crack Kit", collection: "injection", equipmentType: "Injection accessory kit", price: 890, highlight: "Packers, ports, and surface seal for a first injection job", power: "None", dimensions: "Kit case 22 in", weightLbs: 18, tradeTypes: ["crack injection"], contractorTypes: ["concrete contractor"], tags: ["packers", "ports", "kit"], applications: ["First jobs", "Punch-list cracks", "Training"], intendedUsers: concreteUsers, benefits: ["Assorted packers", "Surface seal", "Labeled case"], included: ["Packers", "Surface seal", "Ports", "Case"], description: "Starter packer and port kit so the pump is not sitting idle while you wait on hardware." },
  { handle: "pavora-dual-head-injection-rig", title: "Pavora Dual-Head Injection Rig", collection: "injection", equipmentType: "Dual injection cart", price: 11200, highlight: "Epoxy and PU on one cart for garage restoration crews", power: "120V dual", dimensions: "Cart 36 × 22 × 42 in", weightLbs: 186, tradeTypes: ["crack injection", "garage restoration"], contractorTypes: ["restoration contractor", "parking garage"], tags: ["dual", "injection", "garage"], applications: ["Mixed crack programs", "Garage soffits", "Plaza decks"], intendedUsers: concreteUsers, benefits: ["Two chemistries, one trip", "Hose reels", "Spill tray"], included: ["Cart", "EP pump", "PU pump", "Reels"], description: "Dual-head cart so a garage crew can inject structural epoxy and water-stop PU without swapping machines mid-bay." },
  { handle: "pavora-liftfoam-200", title: "Pavora Liftfoam-200 Slab Rig", collection: "leveling", equipmentType: "Polyurethane slab-jacking rig", price: 18900, featured: true, highlight: "Drill small ports and raise sunken slabs with expanding foam", power: "240V + onboard compressor", dimensions: "Trailer 8 × 5 ft", weightLbs: 1420, tradeTypes: ["slab leveling", "foam injection"], contractorTypes: ["concrete contractor", "paving contractor"], tags: ["foam", "leveling", "slab jacking"], applications: ["Sunken sidewalks", "Warehouse slabs", "Pool decks", "Approach slabs"], intendedUsers: ["Concrete contractors", "Municipal crews", "Property managers"], benefits: ["Small ports", "Controlled lift", "Fast cure"], included: ["Foam rig", "Guns", "Hoses", "Drill template"], description: "Polyurethane leveling rig that raises sunken slabs through dime-size holes. Faster than mudjacking and cleaner on occupied sites." },
  { handle: "pavora-probe-drill-cart", title: "Pavora Probe-Drill Cart", collection: "leveling", equipmentType: "Port drill cart", price: 3200, highlight: "Repeatable hole pattern for foam ports", power: "120V hammer drill", dimensions: "Cart 28 × 18 × 40 in", weightLbs: 74, tradeTypes: ["slab leveling"], contractorTypes: ["concrete contractor"], tags: ["drill", "ports", "leveling"], applications: ["Port layout", "Sidewalks", "Slabs on grade"], intendedUsers: concreteUsers, benefits: ["Template jig", "Dust shroud", "Depth stop"], included: ["Cart", "Hammer drill", "Bits", "Template"], description: "Port-drill cart that keeps hole spacing honest so foam lift is even instead of a series of volcanoes." },
  { handle: "pavora-foam-gun-kit", title: "Pavora Foam-Gun Kit", collection: "leveling", equipmentType: "Injection gun kit", price: 1450, highlight: "Spare guns and mix tips for a second operator", power: "None", dimensions: "Case 20 in", weightLbs: 12, tradeTypes: ["slab leveling"], contractorTypes: ["concrete contractor"], tags: ["foam", "gun", "tips"], applications: ["Second gun", "Remote pours"], intendedUsers: concreteUsers, benefits: ["Quick-connect", "Spare tips", "Flush solvent"], included: ["Two guns", "Tips", "Flush bottle"], description: "Spare foam guns and mix tips so a two-person lift does not share one trigger." },
  { handle: "pavora-melt-120-melter", title: "Pavora Melt-120 Crack Melter", collection: "crack-sealing", equipmentType: "Asphalt crack melter", price: 9800, featured: true, highlight: "120-gallon melter for parking-lot and commercial crack programs", power: "Diesel burner", dimensions: "Trailer 10 ft", weightLbs: 1680, tradeTypes: ["crack sealing", "asphalt"], contractorTypes: ["paving contractor", "property management"], tags: ["melter", "crack", "asphalt"], applications: ["Parking lots", "Drives", "Commercial asphalt"], intendedUsers: paveUsers, benefits: ["Even melt", "Agitator", "Hose reel"], included: ["Melter", "Wand", "Hose", "Starter sealant"], description: "Diesel-fired crack melter sized for lots that take a full day, not a driveway kettle." },
  { handle: "pavora-wand-pro-applicator", title: "Pavora Wand-Pro Applicator", collection: "crack-sealing", equipmentType: "Sealant wand", price: 2100, highlight: "Heated wand with shoe options for overband or flush fill", power: "Heated from kettle", dimensions: "Wand 6 ft", weightLbs: 18, tradeTypes: ["crack sealing"], contractorTypes: ["paving contractor"], tags: ["wand", "overband", "asphalt"], applications: ["Overband", "Flush fill", "Detail cracks"], intendedUsers: paveUsers, benefits: ["Shoe swap", "Heat hold", "Trigger lock"], included: ["Wand", "Two shoes", "Scraper"], description: "Heated applicator wand for overband or flush-fill crack sealing on commercial asphalt." },
  { handle: "pavora-kettle-40-trailer", title: "Pavora Kettle-40 Trailer", collection: "crack-sealing", equipmentType: "Crack-seal trailer", price: 16400, featured: true, highlight: "Ready-to-tow kettle for municipal and HOA routes", power: "Diesel", dimensions: "Trailer 12 ft", weightLbs: 2100, useCase: "both", tradeTypes: ["crack sealing", "municipal"], contractorTypes: ["paving contractor", "municipal"], tags: ["trailer", "kettle", "municipal"], applications: ["City streets", "HOA roads", "Lots"], intendedUsers: paveUsers, benefits: ["Tow-ready", "Arrow board mount", "Tool box"], included: ["Trailer kettle", "Wand", "Cone rack"], description: "Towable 40-series kettle for municipal crack routes and commercial lots. Quote includes freight and burner commissioning." },
  { handle: "pavora-coat-spray-300", title: "Pavora Coat-Spray 300", collection: "sealcoating", equipmentType: "Sealcoat spray system", price: 7200, featured: true, highlight: "Spray or squeegee sealer over aging asphalt before striping", power: "Honda 13 hp", dimensions: "Skid 6 × 4 ft", weightLbs: 640, tradeTypes: ["sealcoating", "asphalt"], contractorTypes: ["paving contractor", "striping contractor"], tags: ["sealcoat", "spray", "asphalt"], applications: ["Parking lots", "Drives", "HOA streets"], intendedUsers: paveUsers, benefits: ["Spray and squeegee", "Agitated tank", "Hose reel"], included: ["Spray skid", "Wands", "Squeegees", "Hose"], description: "Sealcoat spray skid that also squeegees. The right add-on before a striping crew hits the lot." },
  { handle: "pavora-mix-tank-550", title: "Pavora Mix-Tank 550", collection: "sealcoating", equipmentType: "Sealcoat mix tank", price: 5400, highlight: "550-gallon agitated tank for sanded sealer mixes", power: "Engine drive", dimensions: "Tank 8 ft", weightLbs: 880, tradeTypes: ["sealcoating"], contractorTypes: ["paving contractor"], tags: ["tank", "mix", "sealcoat"], applications: ["Sanded mixes", "Bulk sealer", "Crew staging"], intendedUsers: paveUsers, benefits: ["Paddle mix", "Baffle", "Clean-out"], included: ["Tank", "Paddles", "Outlet kit"], description: "Agitated mix tank for sanded sealcoat so the sand does not settle in the first hour." },
  { handle: "pavora-squeegee-crew-kit", title: "Pavora Squeegee Crew Kit", collection: "sealcoating", equipmentType: "Hand tool kit", price: 680, highlight: "Squeegees, brushes, and edging tools for a three-person crew", power: "None", dimensions: "Bundle", weightLbs: 42, tradeTypes: ["sealcoating"], contractorTypes: ["paving contractor"], tags: ["squeegee", "kit"], applications: ["Edges", "Islands", "Touch-up"], intendedUsers: paveUsers, benefits: ["Matched widths", "Replaceable blades"], included: ["Squeegees", "Brushes", "Edgers"], description: "Hand tools for edges and islands the spray wand should not flood." },
  { handle: "pavora-thermark-handliner", title: "Pavora Thermark Handliner", collection: "thermoplastic", equipmentType: "Thermoplastic handliner", price: 14200, featured: true, highlight: "Push liner for crosswalks, stop bars, and bike lanes", power: "Propane melt", dimensions: "Handliner 48 in", weightLbs: 310, useCase: "both", tradeTypes: ["thermoplastic", "road marking"], contractorTypes: ["striping contractor", "municipal"], tags: ["thermoplastic", "crosswalk", "bike lane"], applications: ["Crosswalks", "Stop bars", "Bike lanes", "Arrows"], intendedUsers: stripeUsers, benefits: ["Bead drop", "Screed control", "Quick die change"], included: ["Handliner", "Dies", "Bead hopper", "Torch"], description: "Thermoplastic handliner for high-durability road and lot markings that paint will not survive." },
  { handle: "pavora-thermark-ride", title: "Pavora Thermark Ride", collection: "thermoplastic", equipmentType: "Ride-on thermoplastic applicator", price: 42000, featured: true, highlight: "Ride-on applicator for long-line and intersection programs", power: "Diesel + propane", dimensions: "Ride-on 9 ft", weightLbs: 4200, useCase: "municipal", tradeTypes: ["thermoplastic", "road marking"], contractorTypes: ["striping contractor", "municipal"], tags: ["ride-on", "thermoplastic", "highway"], applications: ["Long lines", "Intersections", "Lane lines"], intendedUsers: stripeUsers, benefits: ["Operator seat", "Bead guns", "Skip-line timer"], included: ["Ride-on", "Dies", "Bead system"], description: "Ride-on thermoplastic machine for municipal and highway subcontract work. Quoted with freight and commissioning." },
  { handle: "pavora-bead-drop-hopper", title: "Pavora Bead-Drop Hopper", collection: "thermoplastic", equipmentType: "Glass bead hopper", price: 3900, highlight: "Retroreflectivity beads metered behind the screed", power: "None / 12V agitator", dimensions: "Hopper 24 in", weightLbs: 86, tradeTypes: ["thermoplastic", "beads"], contractorTypes: ["striping contractor", "municipal"], tags: ["beads", "retroreflectivity"], applications: ["Night visibility", "DOT specs"], intendedUsers: stripeUsers, benefits: ["Even drop", "Agitator", "Quick dump"], included: ["Hopper", "Gate", "Mount"], description: "Bead hopper that meters glass beads into hot thermoplastic for night visibility." },
  { handle: "pavora-stripe-mill-12", title: "Pavora Stripe-Mill 12", collection: "marking-removal", equipmentType: "Line removal grinder", price: 8600, featured: true, highlight: "12-inch mill that erases old parking lines without wrecking the asphalt", power: "Honda 13 hp", dimensions: "Walk-behind 36 in", weightLbs: 268, tradeTypes: ["marking removal", "grinding"], contractorTypes: ["striping contractor", "paving contractor"], tags: ["removal", "grind", "lines"], applications: ["Parking lines", "Arrows", "Legends"], intendedUsers: stripeUsers, benefits: ["Depth control", "Vac port", "Narrow drum"], included: ["Mill", "Drum", "Vac adapter"], description: "Walk-behind line mill for removing old paint and thermoplastic without gouging the lot." },
  { handle: "pavora-waterblast-line", title: "Pavora Waterblast-Line", collection: "marking-removal", equipment: "Ultra-high pressure line blaster", equipmentType: "Water-blast line remover", price: 21500, highlight: "UHP water that lifts markings with less scar than a mill", power: "Diesel 40 hp", dimensions: "Trailer 10 ft", weightLbs: 2800, tradeTypes: ["marking removal", "water blasting"], contractorTypes: ["striping contractor", "municipal"], tags: ["waterblast", "removal", "uHP"], applications: ["Highway legends", "Airport marks", "Sensitive asphalt"], intendedUsers: stripeUsers, benefits: ["Less scar", "Recover water option", "Adjustable pressure"], included: ["UHP unit", "Lance", "Hose", "Trailer"], description: "Ultra-high-pressure water blaster for marking removal on asphalt that cannot take a deep mill scar." },
  { handle: "pavora-shot-erase-cart", title: "Pavora Shot-Erase Cart", collection: "marking-removal", equipmentType: "Shot-blast eraser", price: 11200, highlight: "Recirculating shot that dulls and removes paint on decks", power: "230V", dimensions: "Cart 40 in", weightLbs: 420, tradeTypes: ["marking removal", "shot blast"], contractorTypes: ["striping contractor", "parking garage"], tags: ["shot", "erase", "garage"], applications: ["Garage decks", "Warehouse floors", "Paint removal"], intendedUsers: stripeUsers, benefits: ["Media recycle", "Dust sealed", "Edge kit"], included: ["Cart", "Shot load", "Dust hose"], description: "Shot-blast cart that removes paint on garage decks and warehouse floors with recirculating media." },
  { handle: "pavora-cryo-40-blaster", title: "Pavora Cryo-40 Dry-Ice Blaster", collection: "dry-ice", equipmentType: "Dry-ice blaster", price: 16800, featured: true, highlight: "Non-abrasive CO₂ cleaning for machinery, electrics, and molds", power: "480V 3Ø + air", dimensions: "Skid 48 × 28 × 42 in", weightLbs: 510, tradeTypes: ["dry-ice blasting", "industrial cleaning"], contractorTypes: ["blasting contractor", "restoration contractor"], tags: ["dry ice", "co2", "non-abrasive"], applications: ["Machinery", "Electrical cabinets", "Molds", "Fire restoration"], intendedUsers: blastUsers, benefits: ["No secondary waste", "Non-conductive media", "Variable pellet"], included: ["Blaster", "Hoses", "Nozzles", "Pellet hopper"], description: "Dry-ice blaster for industrial cleaning where sand or soda would damage the substrate or leave grit in a plant." },
  { handle: "pavora-cryo-hopper", title: "Pavora Cryo Hopper", collection: "dry-ice", equipmentType: "Pellet hopper", price: 4200, highlight: "Insulated hopper that keeps pellets from sintering on a hot job", power: "None", dimensions: "Hopper 30 in", weightLbs: 96, tradeTypes: ["dry-ice blasting"], contractorTypes: ["blasting contractor"], tags: ["hopper", "pellets"], applications: ["Jobsite staging", "Long blasts"], intendedUsers: blastUsers, benefits: ["Insulation", "Slide gate", "Fork pockets"], included: ["Hopper", "Lid", "Gate"], description: "Insulated dry-ice hopper so pellets last through a shift instead of turning into a brick." },
  { handle: "pavora-cryo-pellet-maker", title: "Pavora Cryo Pellet Maker", collection: "dry-ice", equipmentType: "Pelletizer", price: 9800, highlight: "Make pellets on site when the ice truck is late", power: "240V + LCO2", dimensions: "Skid 40 in", weightLbs: 380, tradeTypes: ["dry-ice blasting"], contractorTypes: ["blasting contractor"], tags: ["pelletizer", "dry ice"], applications: ["On-site production", "Remote plants"], intendedUsers: blastUsers, benefits: ["3 mm pellets", "On demand", "Less waste"], included: ["Pelletizer", "Die", "Insulated bin"], description: "On-site pelletizer for crews that cannot wait on a dry-ice delivery." },
  { handle: "pavora-soda-pro-250", title: "Pavora Soda-Pro 250", collection: "soda", equipmentType: "Soda blast pot", price: 6400, featured: true, highlight: "Sodium bicarbonate blasting for paint and grime without heavy profile", power: "Requires 185 cfm air", dimensions: "Pot 36 in", weightLbs: 210, tradeTypes: ["soda blasting", "coating removal"], contractorTypes: ["blasting contractor", "restoration contractor"], tags: ["soda", "paint removal", "blast"], applications: ["Buildings", "Machinery", "Vehicles", "Fire soot"], intendedUsers: blastUsers, benefits: ["Soft abrasive", "Moisture trap", "Metering valve"], included: ["Pot", "Hose", "Nozzles", "Moisture trap"], description: "Soda blast pot for stripping paint and contaminants where sand would cut too deep." },
  { handle: "pavora-soda-pot-80", title: "Pavora Soda-Pot 80", collection: "soda", equipmentType: "Compact soda pot", price: 2100, highlight: "Eighty-pound pot for detail and vehicle work", power: "Shop air", dimensions: "Pot 22 in", weightLbs: 64, tradeTypes: ["soda blasting"], contractorTypes: ["blasting contractor"], tags: ["soda", "compact"], applications: ["Vehicles", "Trim", "Small parts"], intendedUsers: blastUsers, benefits: ["Portable", "Fine metering"], included: ["Pot", "Hose", "Nozzle"], description: "Compact soda pot for vehicles and detail work that does not need a 250-pound pot." },
  { handle: "pavora-media-vac-recovery", title: "Pavora Media-Vac Recovery", collection: "soda", equipmentType: "Media vacuum", price: 4800, highlight: "Recover soda and debris instead of leaving a white drift", power: "230V", dimensions: "Vac 28 × 22 × 40 in", weightLbs: 142, tradeTypes: ["soda blasting", "cleanup"], contractorTypes: ["blasting contractor"], tags: ["vac", "recovery", "soda"], applications: ["Interior blast", "Shops", "Occupied sites"], intendedUsers: blastUsers, benefits: ["Cyclone", "HEPA option", "Dump drum"], included: ["Vac", "Hose", "Cyclone"], description: "Recovery vacuum so soda blasting indoors does not become a bicarbonate snowstorm." },
  { handle: "pavora-lase-200-fiber", title: "Pavora Lase-200 Fiber Cleaner", collection: "laser", equipmentType: "200W fiber laser cleaner", price: 28500, featured: true, highlight: "Strip rust, paint, and residue with light instead of grit", power: "240V 1Ø", dimensions: "Cart 32 × 22 × 44 in", weightLbs: 186, tradeTypes: ["laser cleaning", "surface prep"], contractorTypes: ["blasting contractor", "restoration contractor"], tags: ["laser", "rust", "cleaning"], applications: ["Rust", "Paint", "Molds", "Welds"], intendedUsers: blastUsers, benefits: ["No media waste", "Precise", "Low substrate damage"], included: ["Laser cart", "Gun", "Goggles", "Chiller"], description: "200-watt fiber laser cleaner for rust and coating removal without abrasive waste. Quoted with safety package." },
  { handle: "pavora-lase-handheld-50", title: "Pavora Lase-Handheld 50", collection: "laser", equipmentType: "50W handheld laser", price: 12400, highlight: "Handheld unit for welds, fixtures, and restoration details", power: "120V", dimensions: "Case 22 in", weightLbs: 28, tradeTypes: ["laser cleaning"], contractorTypes: ["blasting contractor", "restoration contractor"], tags: ["laser", "handheld"], applications: ["Welds", "Fixtures", "Detail rust"], intendedUsers: blastUsers, benefits: ["Portable", "Air cooled", "Class safety kit"], included: ["Handheld", "Goggles", "Case"], description: "50-watt handheld laser for detail cleaning where a 200-watt cart is overkill." },
  { handle: "pavora-lase-cart-100", title: "Pavora Lase-Cart 100", collection: "laser", equipmentType: "100W laser cart", price: 18900, highlight: "Mid-power cart for shops that run laser cleaning daily", power: "240V", dimensions: "Cart 30 in", weightLbs: 154, tradeTypes: ["laser cleaning"], contractorTypes: ["blasting contractor"], tags: ["laser", "cart"], applications: ["Shop work", "Molds", "Parts"], intendedUsers: blastUsers, benefits: ["Water cooled", "Interlock", "Fume port"], included: ["Cart", "Gun", "Chiller", "Fume adapter"], description: "100-watt laser cart for shops that clean parts and molds every day." },
  { handle: "pavora-wash-4000-trailer", title: "Pavora Wash-4000 Trailer", collection: "pressure-wash", equipmentType: "Hot-water pressure washer trailer", price: 8900, featured: true, highlight: "4000 PSI hot wash for docks, garages, and building exteriors", power: "Honda + diesel burner", dimensions: "Trailer 8 ft", weightLbs: 1180, tradeTypes: ["pressure washing", "hot water"], contractorTypes: ["restoration contractor", "property management"], tags: ["pressure wash", "hot water", "trailer"], applications: ["Warehouses", "Parking garages", "Loading docks", "Exteriors"], intendedUsers: ["Pressure-wash contractors", "Property managers", "Restoration crews"], benefits: ["Hot water", "Hose reel", "Chemical injector"], included: ["Trailer washer", "Hoses", "Surface cleaner mount"], description: "Hot-water trailer washer for commercial exteriors, docks, and garage decks." },
  { handle: "pavora-wash-hot-8gpm", title: "Pavora Wash-Hot 8 GPM", collection: "pressure-wash", equipmentType: "Skid hot washer", price: 11200, highlight: "Eight gallons a minute for fleet and industrial wash bays", power: "Diesel", dimensions: "Skid 5 × 3 ft", weightLbs: 640, tradeTypes: ["pressure washing"], contractorTypes: ["restoration contractor"], tags: ["8 gpm", "hot", "industrial"], applications: ["Fleet", "Industrial", "Food plants"], intendedUsers: ["Industrial cleaners"], benefits: ["High flow", "Belt drive", "Downstream chem"], included: ["Skid", "Gun", "Hose"], description: "High-flow hot washer for industrial bays that a 4 GPM machine cannot keep up with." },
  { handle: "pavora-surface-cleaner-21", title: "Pavora Surface-Cleaner 21", collection: "pressure-wash", equipmentType: "Rotary surface cleaner", price: 1450, highlight: "21-inch deck that leaves even wash paths on lots and sidewalks", power: "From washer", dimensions: '21" deck', weightLbs: 38, tradeTypes: ["pressure washing"], contractorTypes: ["restoration contractor", "property management"], tags: ["surface cleaner", "sidewalk"], applications: ["Sidewalks", "Lots", "Plaza decks"], intendedUsers: ["Pressure-wash contractors"], benefits: ["Even path", "Splash guard", "Swivel"], included: ["Deck", "Tips", "Handle"], description: "Rotary surface cleaner so sidewalks and lots do not look zebra-striped." },
  { handle: "pavora-wash-cart-3000", title: "Pavora Wash-Cart 3000", collection: "pressure-wash", equipmentType: "Cold-water cart washer", price: 3200, highlight: "3000 PSI cart for interiors and occupied sites", power: "230V", dimensions: "Cart 28 in", weightLbs: 164, tradeTypes: ["pressure washing"], contractorTypes: ["restoration contractor"], tags: ["electric", "indoor", "wash"], applications: ["Interiors", "Food plants", "Garages"], intendedUsers: ["Pressure-wash contractors"], benefits: ["Electric", "Quiet", "No exhaust"], included: ["Cart", "Hose", "Gun"], description: "Electric cold washer for interiors where a gas engine is not allowed." },
  { handle: "pavora-lotline-walk", title: "Pavora Lotline Walk", collection: "lot-painting", equipmentType: "Walk-behind striper", price: 5400, featured: true, highlight: "Airless walk-behind for stalls, arrows, and hash marks", power: "Honda 4-stroke", dimensions: "Walk-behind 40 in", weightLbs: 148, tradeTypes: ["parking lot painting", "striping"], contractorTypes: ["striping contractor", "paving contractor"], tags: ["striper", "parking lot", "paint"], applications: ["Stalls", "Arrows", "Hash", "Fire lanes"], intendedUsers: stripeUsers, benefits: ["Line width 2–6 in", "Bead option", "Pointer", "Stencil tray"], included: ["Striper", "Gun", "Pointers", "Hopper"], description: "Walk-behind airless striper for parking lots. The machine most striping companies actually live on." },
  { handle: "pavora-lotline-ride", title: "Pavora Lotline Ride", collection: "lot-painting", equipmentType: "Ride-on lot striper", price: 18600, featured: true, highlight: "Ride-on painter for large lots and warehouse floors", power: "Honda 13 hp", dimensions: "Ride-on 7 ft", weightLbs: 860, tradeTypes: ["parking lot painting", "striping"], contractorTypes: ["striping contractor"], tags: ["ride-on", "lot", "paint"], applications: ["Large lots", "Warehouses", "Airfields"], intendedUsers: stripeUsers, benefits: ["Two guns", "Skip timer", "Seat"], included: ["Ride-on", "Guns", "Bead tanks"], description: "Ride-on lot painter for crews that stripe acres, not a dozen stalls." },
  { handle: "pavora-stencil-bank", title: "Pavora Stencil Bank", collection: "lot-painting", equipmentType: "Stencil set", price: 890, highlight: "Arrows, handicap, stop, and number stencils in one crate", power: "None", dimensions: "Crate 48 in", weightLbs: 54, tradeTypes: ["parking lot painting"], contractorTypes: ["striping contractor"], tags: ["stencils", "ada", "arrows"], applications: ["ADA", "Arrows", "Numbers"], intendedUsers: stripeUsers, benefits: ["0.125 in plastic", "Grommets", "Nested crate"], included: ["Stencil set", "Crate", "Weights"], description: "Commercial stencil bank so the lot gets legal legends, not chalked guesses." },
  { handle: "pavora-airless-stripe", title: "Pavora Airless-Stripe", collection: "lot-painting", equipmentType: "Airless paint sprayer", price: 2800, highlight: "Airless cart for curbs, islands, and touch-up", power: "120V", dimensions: "Cart 24 in", weightLbs: 72, tradeTypes: ["parking lot painting"], contractorTypes: ["striping contractor"], tags: ["airless", "curb", "paint"], applications: ["Curbs", "Islands", "Touch-up"], intendedUsers: stripeUsers, benefits: ["Fine tip", "Hose 50 ft", "Hopper"], included: ["Sprayer", "Tips", "Hose"], description: "Airless cart for curbs and islands the walk-behind striper cannot hug." },
  { handle: "pavora-skydeck-rtk", title: "Pavora Skydeck RTK", collection: "drone", equipmentType: "RTK inspection drone", price: 9200, featured: true, highlight: "RTK drone for commercial roof photo sets with survey-grade position", power: "Battery", dimensions: "Case 22 in", weightLbs: 12, tradeTypes: ["drone inspection", "roof"], contractorTypes: ["roofing contractor", "property management"], tags: ["drone", "rtk", "roof"], applications: ["Roof surveys", "After-storm", "Warranty docs"], intendedUsers: roofUsers, benefits: ["RTK", "Obstacle sensing", "Mission planner"], included: ["Drone", "Batteries ×4", "Controller", "Case"], description: "RTK inspection drone for commercial roofs. Photographic reports without sending a person onto a 4:12 in July." },
  { handle: "pavora-skydeck-thermal", title: "Pavora Skydeck Thermal", collection: "drone", equipmentType: "Thermal inspection drone", price: 14800, featured: true, highlight: "Radiometric thermal + RGB for leak hunts from the air", power: "Battery", dimensions: "Case 24 in", weightLbs: 14, tradeTypes: ["drone inspection", "thermal", "roof"], contractorTypes: ["roofing contractor", "property management"], tags: ["drone", "thermal", "leak"], applications: ["Moisture mapping", "Night surveys", "Flat roofs"], intendedUsers: roofUsers, benefits: ["Radiometric", "RGB overlay", "Report export"], included: ["Thermal drone", "Batteries", "Software seat"], description: "Thermal + RGB drone for roof leak detection from the air. Pair with a handheld IR camera for confirmation." },
  { handle: "pavora-roof-report-station", title: "Pavora Roof-Report Station", collection: "drone", equipmentType: "Field reporting laptop kit", price: 2100, highlight: "Rugged station that compiles photo and thermal reports on site", power: "Battery / 120V", dimensions: "Case 18 in", weightLbs: 9, tradeTypes: ["drone inspection", "reporting"], contractorTypes: ["roofing contractor"], tags: ["report", "laptop", "roof"], applications: ["Client PDFs", "Insurance", "Punch lists"], intendedUsers: roofUsers, benefits: ["Templates", "GPS stamp", "Offline"], included: ["Rugged laptop", "Templates", "Case"], description: "Field station that turns a flight into a client PDF before you leave the lot." },
  { handle: "pavora-thermascan-pro", title: "Pavora Thermascan Pro", collection: "thermal", equipmentType: "Radiometric IR camera", price: 7800, featured: true, highlight: "Handheld infrared for moisture intrusion without tearing the roof", power: "Battery", dimensions: "Camera 11 in", weightLbs: 2, tradeTypes: ["thermal inspection", "leak detection"], contractorTypes: ["roofing contractor", "property management"], tags: ["infrared", "thermal", "moisture"], applications: ["Flat roofs", "Walls", "Plaza decks"], intendedUsers: roofUsers, benefits: ["Radiometric JPEGs", "Laser pointer", "Wi-Fi to report station"], included: ["Camera", "Lenses", "Batteries", "Case"], description: "Handheld radiometric camera for finding wet insulation without a tear-off." },
  { handle: "pavora-moisture-meter-kit", title: "Pavora Moisture-Meter Kit", collection: "thermal", equipmentType: "Moisture meter kit", price: 640, highlight: "Confirm IR hits with pin and pinless meters", power: "Battery", dimensions: "Kit 14 in", weightLbs: 4, tradeTypes: ["leak detection"], contractorTypes: ["roofing contractor"], tags: ["moisture", "meter"], applications: ["Confirm wet insulation", "Decks", "Walls"], intendedUsers: roofUsers, benefits: ["Pin and pinless", "Scale charts"], included: ["Two meters", "Probes", "Case"], description: "Moisture meters that confirm what the thermal camera only suggests." },
  { handle: "pavora-ir-roof-array", title: "Pavora IR-Roof Array", collection: "thermal", equipmentType: "Multi-camera IR array", price: 12400, highlight: "Wide-area array for large low-slope roofs after sundown", power: "Battery / 12V", dimensions: "Array bar 48 in", weightLbs: 18, tradeTypes: ["thermal inspection"], contractorTypes: ["roofing contractor"], tags: ["array", "infrared", "roof"], applications: ["Big-box roofs", "Night surveys"], intendedUsers: roofUsers, benefits: ["Wide FOV", "Sync to GPS", "Tripod"], included: ["Array", "Tripod", "Recorder"], description: "Multi-camera infrared array for large low-slope roofs surveyed after sundown." },
  { handle: "pavora-joint-saw-18", title: "Pavora Joint-Saw 18", collection: "expansion-joints", equipmentType: "Walk-behind joint saw", price: 6400, featured: true, highlight: "18-inch saw for removing failed expansion joints in garages", power: "Honda 13 hp", dimensions: "Saw 40 in", weightLbs: 286, tradeTypes: ["expansion joints", "concrete sawing"], contractorTypes: ["restoration contractor", "parking garage"], tags: ["saw", "joint", "garage"], applications: ["Garage joints", "Plaza decks", "Sidewalks"], intendedUsers: envelopeUsers, benefits: ["Depth control", "Vac port", "Water kit"], included: ["Saw", "Blade", "Vac adapter"], description: "Joint saw for cutting out failed expansion joints in parking garages and decks." },
  { handle: "pavora-joint-fill-pump", title: "Pavora Joint-Fill Pump", collection: "expansion-joints", equipmentType: "Joint fill pump", price: 4200, highlight: "Meters silicone or polyurethane into prepared joints", power: "120V", dimensions: "Cart 22 in", weightLbs: 86, tradeTypes: ["expansion joints", "sealant"], contractorTypes: ["restoration contractor", "parking garage"], tags: ["fill", "sealant", "joint"], applications: ["Garage joints", "Plaza", "Sidewalks"], intendedUsers: envelopeUsers, benefits: ["Ratio meter", "Heat option", "Flush"], included: ["Pump", "Hoses", "Nozzles"], description: "Metered fill pump for silicone and polyurethane joint replacement." },
  { handle: "pavora-garage-joint-kit", title: "Pavora Garage-Joint Kit", collection: "expansion-joints", equipmentType: "Joint replacement kit", price: 1800, highlight: "Backer, primer, and nosing materials for a first bay", power: "None", dimensions: "Pallet kit", weightLbs: 120, tradeTypes: ["expansion joints"], contractorTypes: ["parking garage", "restoration contractor"], tags: ["kit", "backer", "primer"], applications: ["First bay", "Punch list"], intendedUsers: envelopeUsers, benefits: ["Matched materials", "Coverage chart"], included: ["Backer", "Primer", "Nosing", "Chart"], description: "Material kit so the saw and pump are not waiting on a supply house." },
  { handle: "pavora-seal-gun-bulk", title: "Pavora Seal-Gun Bulk", collection: "caulking", equipmentType: "Bulk caulk gun", price: 890, highlight: "Sausage and bulk guns for facade and window joints", power: "None / battery option", dimensions: "Gun 24 in", weightLbs: 6, tradeTypes: ["caulking", "joint sealing"], contractorTypes: ["restoration contractor", "glazing contractor"], tags: ["caulk", "bulk", "facade"], applications: ["Windows", "Facades", "Penetrations"], intendedUsers: envelopeUsers, benefits: ["Bulk and sausage", "Smooth rod", "Nozzle set"], included: ["Two guns", "Nozzles", "Sausage plates"], description: "Bulk and sausage guns for commercial caulking that a hardware-store cartridge gun cannot keep up with." },
  { handle: "pavora-facade-pump", title: "Pavora Facade Pump", collection: "caulking", equipmentType: "Plural-component facade pump", price: 5400, featured: true, highlight: "Pumps silicone and polyurethane to swing-stage crews", power: "120V", dimensions: "Cart 26 in", weightLbs: 118, tradeTypes: ["caulking", "facade"], contractorTypes: ["restoration contractor", "glazing contractor"], tags: ["facade", "pump", "silicone"], applications: ["Curtain wall", "Expansion joints", "Penetrations"], intendedUsers: envelopeUsers, benefits: ["Long hose", "Ratio control", "Stage mount"], included: ["Pump", "100 ft hose", "Guns"], description: "Facade pump that feeds swing-stage caulkers without hauling pails up the elevation." },
  { handle: "pavora-joint-prep-grinder", title: "Pavora Joint-Prep Grinder", collection: "caulking", equipmentType: "Joint prep grinder", price: 2100, highlight: "Opens and cleans joints before sealant so it actually sticks", power: "120V", dimensions: "Tool 16 in", weightLbs: 14, tradeTypes: ["caulking", "prep"], contractorTypes: ["restoration contractor"], tags: ["prep", "grinder", "joint"], applications: ["Failed caulk", "Windows", "Concrete joints"], intendedUsers: envelopeUsers, benefits: ["Dust shroud", "Width guides"], included: ["Grinder", "Wheels", "Shroud"], description: "Joint-prep grinder that removes failed sealant and opens the joint to the right profile." },
  { handle: "pavora-garage-restore-pack", title: "Pavora Garage Restore Pack", collection: "garage", equipmentType: "Restoration package", price: 24600, featured: true, highlight: "Injection, joint, coating, and striping kit for a parking garage bay", power: "Mixed", dimensions: "Freight pallet set", weightLbs: 2100, tradeTypes: ["garage restoration", "injection", "striping", "coatings"], contractorTypes: ["parking garage", "restoration contractor"], tags: ["garage", "package", "restoration"], applications: ["Parking garages", "Plaza decks", "Podiums"], intendedUsers: ["Restoration contractors", "Garage operators"], benefits: ["One freight plan", "Matched chemistries", "Crew briefing"], included: ["Injecta-PU", "Joint-Saw 18", "Joint-Fill Pump", "Lotline Walk", "Coating starter"], description: "Combined package for parking garage restoration: crack injection, joint replacement, striping, and a starter coating set." },
  { handle: "pavora-deck-coat-rig", title: "Pavora Deck-Coat Rig", collection: "garage", equipmentType: "Traffic coating sprayer", price: 9800, highlight: "Plural sprayer for waterproof traffic coatings on garage decks", power: "240V", dimensions: "Cart 36 in", weightLbs: 240, tradeTypes: ["coatings", "waterproofing"], contractorTypes: ["parking garage", "restoration contractor"], tags: ["coating", "waterproof", "garage"], applications: ["Garage decks", "Plaza", "Ramps"], intendedUsers: ["Restoration contractors"], benefits: ["Heated hoses", "Ratio alarm", "Flush"], included: ["Sprayer", "Hoses", "Guns"], description: "Traffic-coating sprayer for waterproof membranes on garage decks and ramps." },
  { handle: "pavora-spall-patch-station", title: "Pavora Spall-Patch Station", collection: "garage", equipmentType: "Spall repair station", price: 3600, highlight: "Mixer, guns, and form kits for overhead and deck spalls", power: "120V", dimensions: "Station 32 in", weightLbs: 96, tradeTypes: ["concrete repair"], contractorTypes: ["parking garage", "restoration contractor"], tags: ["spall", "patch", "garage"], applications: ["Overhead", "Deck", "Columns"], intendedUsers: ["Restoration contractors"], benefits: ["Overhead mix", "Form kit", "Fast set"], included: ["Mixer", "Guns", "Forms"], description: "Spall station for overhead and deck patches that have to take traffic the next morning." },
];

const partRows = [
  { handle: "pavora-diamond-cup-set", title: "Pavora Diamond Cup Set", collection: "parts", equipmentType: "Diamond tooling", price: 420, highlight: "Metal-bond cups for grind and coating removal", power: "None", dimensions: "Box", weightLbs: 8, tradeTypes: ["grinding"], contractorTypes: ["concrete contractor"], tags: ["diamond", "cups"], applications: ["Grind", "Coating removal"], intendedUsers: concreteUsers, benefits: ["Matched grit", "Segmented"], included: ["6 cups"], description: "Diamond cup set for planetary and edge grinders." },
  { handle: "pavora-polish-pad-pack", title: "Pavora Polish Pad Pack", collection: "parts", equipmentType: "Polish pads", price: 280, highlight: "Resin pads from 200 to 3000 grit", power: "None", dimensions: "Box", weightLbs: 6, tradeTypes: ["polishing"], contractorTypes: ["concrete contractor"], tags: ["pads", "polish"], applications: ["Hone", "Polish"], intendedUsers: concreteUsers, benefits: ["Grit labeled"], included: ["Pad set"], description: "Resin polish pads for the Mill and Polish-Pro series." },
  { handle: "pavora-injection-packers", title: "Pavora Injection Packers", collection: "parts", equipmentType: "Packers", price: 160, highlight: "Mechanical packers in three diameters", power: "None", dimensions: "Box", weightLbs: 4, tradeTypes: ["injection"], contractorTypes: ["concrete contractor"], tags: ["packers"], applications: ["Epoxy", "PU"], intendedUsers: concreteUsers, benefits: ["Assorted"], included: ["100 packers"], description: "Mechanical injection packers for epoxy and polyurethane." },
  { handle: "pavora-liftfoam-cartridge", title: "Pavora Liftfoam Cartridge", collection: "parts", equipmentType: "Leveling foam", price: 540, highlight: "Two-component foam for slab lift", power: "None", dimensions: "Drum pair", weightLbs: 88, tradeTypes: ["leveling"], contractorTypes: ["concrete contractor"], tags: ["foam"], applications: ["Slab lift"], intendedUsers: concreteUsers, benefits: ["Consistent rise"], included: ["A/B set"], description: "Polyurethane foam set for Liftfoam rigs." },
  { handle: "pavora-crack-sealant-box", title: "Pavora Crack Sealant Box", collection: "parts", equipmentType: "Hot-pour sealant", price: 210, highlight: "DOT-grade hot-pour in 30-lb boxes", power: "None", dimensions: "Pallet box", weightLbs: 30, tradeTypes: ["crack sealing"], contractorTypes: ["paving contractor"], tags: ["sealant"], applications: ["Lots", "Streets"], intendedUsers: paveUsers, benefits: ["Even melt"], included: ["30 lb"], description: "Hot-pour crack sealant for Pavora melters." },
  { handle: "pavora-sealcoat-drum", title: "Pavora Sealcoat Drum", collection: "parts", equipmentType: "Asphalt sealer", price: 190, highlight: "Refined-tar or asphalt emulsion drum", power: "None", dimensions: "55 gal", weightLbs: 480, tradeTypes: ["sealcoating"], contractorTypes: ["paving contractor"], tags: ["sealer"], applications: ["Lots"], intendedUsers: paveUsers, benefits: ["Sand-ready"], included: ["Drum"], description: "Sealcoat drum for Coat-Spray systems." },
  { handle: "pavora-thermo-blocks", title: "Pavora Thermo Blocks", collection: "parts", equipmentType: "Thermoplastic", price: 320, highlight: "Preformed and bulk thermoplastic in white and yellow", power: "None", dimensions: "Carton", weightLbs: 50, tradeTypes: ["thermoplastic"], contractorTypes: ["striping contractor"], tags: ["thermoplastic"], applications: ["Lines", "Legends"], intendedUsers: stripeUsers, benefits: ["Colorfast"], included: ["50 lb"], description: "Thermoplastic blocks for Thermark liners." },
  { handle: "pavora-glass-beads", title: "Pavora Glass Beads", collection: "parts", equipmentType: "Drop-on beads", price: 85, highlight: "Type I glass beads for night visibility", power: "None", dimensions: "Bag", weightLbs: 50, tradeTypes: ["thermoplastic", "lot painting"], contractorTypes: ["striping contractor"], tags: ["beads"], applications: ["Retroreflectivity"], intendedUsers: stripeUsers, benefits: ["Graded"], included: ["50 lb bag"], description: "Drop-on glass beads for paint and thermoplastic." },
  { handle: "pavora-soda-media", title: "Pavora Soda Media", collection: "parts", equipmentType: "Bicarbonate media", price: 95, highlight: "Food-grade sodium bicarbonate blast media", power: "None", dimensions: "Bag", weightLbs: 50, tradeTypes: ["soda blasting"], contractorTypes: ["blasting contractor"], tags: ["soda", "media"], applications: ["Paint", "Soot"], intendedUsers: blastUsers, benefits: ["Low moisture"], included: ["50 lb"], description: "Soda blast media for Soda-Pro pots." },
  { handle: "pavora-dry-ice-order", title: "Pavora Dry-Ice Order", collection: "parts", equipmentType: "CO₂ pellets", price: 240, highlight: "Pellets delivered when a pelletizer is not on the truck", power: "None", dimensions: "Insulated bin", weightLbs: 200, tradeTypes: ["dry-ice blasting"], contractorTypes: ["blasting contractor"], tags: ["dry ice"], applications: ["Blasting"], intendedUsers: blastUsers, benefits: ["3 mm"], included: ["200 lb"], description: "Dry-ice pellet order for Cryo blasters." },
  { handle: "pavora-lot-paint-pail", title: "Pavora Lot Paint Pail", collection: "parts", equipmentType: "Traffic paint", price: 78, highlight: "Fast-dry acrylic in white, yellow, and blue", power: "None", dimensions: "5 gal", weightLbs: 55, tradeTypes: ["parking lot painting"], contractorTypes: ["striping contractor"], tags: ["paint"], applications: ["Stalls", "Arrows"], intendedUsers: stripeUsers, benefits: ["Fast dry"], included: ["5 gal"], description: "Traffic paint for Lotline stripers." },
  { handle: "pavora-hepa-filters", title: "Pavora HEPA Filters", collection: "parts", equipmentType: "Filters", price: 140, highlight: "Primary and HEPA set for Vac Prop extractors", power: "None", dimensions: "Box", weightLbs: 5, tradeTypes: ["dust control"], contractorTypes: ["concrete contractor"], tags: ["hepa", "filter"], applications: ["Grinders"], intendedUsers: concreteUsers, benefits: ["Sealed"], included: ["Filter set"], description: "Replacement HEPA and primary filters." },
];

const packageRows = [
  { handle: "pavora-concrete-floor-crew", title: "Pavora Concrete Floor Crew", collection: "packages", equipmentType: "Crew package", price: 21400, featured: true, highlight: "Grinder, edge, vac, and cups for a first polish crew", power: "Mixed", dimensions: "Freight set", weightLbs: 820, tradeTypes: ["grinding", "polishing"], contractorTypes: ["concrete contractor"], tags: ["package", "floor"], applications: ["Commercial floors"], intendedUsers: concreteUsers, benefits: ["Matched dust path", "One freight"], included: ["Mill-27", "Dens-7", "HEPA-Vac", "Cup set"], description: "First-crew package for grind and polish: planetary, edge, HEPA vac, and starter diamonds." },
  { handle: "pavora-lot-maintenance-crew", title: "Pavora Lot Maintenance Crew", collection: "packages", equipmentType: "Crew package", price: 16800, featured: true, highlight: "Crack seal, sealcoat, and striping for property-management routes", power: "Mixed", dimensions: "Freight set", weightLbs: 2600, tradeTypes: ["crack sealing", "sealcoating", "lot painting"], contractorTypes: ["paving contractor", "striping contractor"], tags: ["package", "lot"], applications: ["HOA", "Retail lots"], intendedUsers: paveUsers, benefits: ["Seal then stripe", "One invoice"], included: ["Melt-120", "Coat-Spray 300", "Lotline Walk", "Stencils"], description: "Lot-maintenance package: melt, sealcoat, and stripe as one freight plan." },
  { handle: "pavora-marking-crew", title: "Pavora Marking Crew", collection: "packages", equipmentType: "Crew package", price: 26800, highlight: "Thermoplastic liner plus line mill for cities that rewrite intersections", power: "Mixed", dimensions: "Freight set", weightLbs: 980, useCase: "municipal", tradeTypes: ["thermoplastic", "marking removal"], contractorTypes: ["striping contractor", "municipal"], tags: ["package", "marking"], applications: ["Intersections", "Schools"], intendedUsers: stripeUsers, benefits: ["Remove then apply"], included: ["Thermark Handliner", "Stripe-Mill 12", "Beads", "Dies"], description: "Marking package: remove the old legend, lay thermoplastic, drop beads." },
  { handle: "pavora-blast-shop-crew", title: "Pavora Blast Shop Crew", collection: "packages", equipmentType: "Crew package", price: 19800, highlight: "Soda pot, recovery vac, and media for a restoration shop", power: "Mixed", dimensions: "Freight set", weightLbs: 420, tradeTypes: ["soda blasting"], contractorTypes: ["blasting contractor", "restoration contractor"], tags: ["package", "blast"], applications: ["Shop", "Fire restoration"], intendedUsers: blastUsers, benefits: ["Contain the media"], included: ["Soda-Pro 250", "Media-Vac", "Soda media"], description: "Shop blasting package with recovery so soda stays in the drum." },
  { handle: "pavora-roof-intel-crew", title: "Pavora Roof Intel Crew", collection: "packages", equipmentType: "Crew package", price: 17200, highlight: "RTK drone, thermal camera, and report station for roofing companies", power: "Battery", dimensions: "Two cases", weightLbs: 28, tradeTypes: ["drone inspection", "thermal"], contractorTypes: ["roofing contractor"], tags: ["package", "roof"], applications: ["Commercial roofs"], intendedUsers: roofUsers, benefits: ["Photo + thermal + PDF"], included: ["Skydeck RTK", "Thermascan Pro", "Report Station"], description: "Roof intelligence package: fly, scan, confirm moisture, deliver the PDF." },
  { handle: "pavora-envelope-crew", title: "Pavora Envelope Crew", collection: "packages", equipmentType: "Crew package", price: 9400, highlight: "Facade pump, prep grinder, and bulk guns for joint programs", power: "120V", dimensions: "Freight set", weightLbs: 160, tradeTypes: ["caulking", "expansion joints"], contractorTypes: ["restoration contractor"], tags: ["package", "envelope"], applications: ["Facades", "Windows"], intendedUsers: envelopeUsers, benefits: ["Prep then pump"], included: ["Facade Pump", "Joint-Prep Grinder", "Seal-Gun Bulk"], description: "Building-envelope package for commercial caulking and joint sealing." },
];

for (const row of [...rows, ...partRows, ...packageRows]) add(row);

const catalog = {
  brand: "Pavora",
  generatedAt: new Date().toISOString(),
  collections,
  products,
};

writeFileSync(join(root, "data", "catalog.json"), JSON.stringify(catalog, null, 2));
console.log(`Wrote ${products.length} products across ${collections.length} collections`);
